name: Release

on:
  push:
    branches:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.head_commit.message, 'release') }}

    steps:
      - uses: actions/checkout@v2
      - name: Sed
        run:
          java-version: 12
          distribution: 'adopt'
