name: Release
on:
  push:
    paths:
      - 'scripts/**'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.head_commit.message, '[Release]') }}
    steps:
    - uses: actions/checkout@v2
    
    - name: Sed Scripts
      run: |
        sed -i "s/online-scripts/local-scripts/g" `grep online-scripts -rl scripts`

    - name: Push file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'scripts/*'
        destination_repo: 'pzcn/MIUI-Icons-APP'
        destination_folder: 'pio/src/main/assets/script'
        user_email: 'sdustpedro@gmail.com'
        user_name: 'pzcn'
        destination_branch: 'local'