name: Release
on:
  push:
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.head_commit.message, 'push') }}
    steps:
    - uses: actions/checkout@v2
    
    - name: Sed Scripts
      run: |
        sed -i "s/online-scripts/local-scripts/g" `grep online-scripts -rl scripts`
        sed -i "s/公告-Beta/公告/g" scripts/more.xml
        sed -i "s/Announcement-Beta/Announcement/g" scripts/eng/more.xml

    - name: Push file
      uses: crykn/copy_folder_to_another_repo_action@v1.0.6
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: 'scripts'
        destination_repo: 'pzcn/MIUI-Icons-APP'
        destination_folder: 'pio/src/main/assets/local-scripts'
        destination_branch: 'main'
        user_email: 'sdustpedro@gmail.com'
        user_name: 'pzcn'
        
