name: Update scripts
on:
  push:
    paths:
      - 'scripts/**'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update Scripts
      run: |
        cd scripts
        tar -cvf script2.tar *
        :> script2.ini
        echo "md5=`md5sum ./script2.tar|cut -d ' ' -f1`" >> ./script2.ini
        echo "script_version=$(TZ=':Asia/Shanghai' date '+%Y%m%d%H%M')" >> ./script2.ini
        curl -T script2.tar -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/script251.tar?version=latest"
        curl -T script2.ini -u ${{secrets.coding_password}} "https://miuiicons-generic.pkg.coding.net/icons/files/script251.ini?version=latest"